/* PrintSheet.jsx — Handwriting Practice Template for Printing */
import './PrintSheet.css';

export function PrintSheet({ character, pinyin, meaning }) {
  // Create a 10x12 grid for practice
  const gridCount = 120;
  const grids = Array.from({ length: gridCount });

  return (
    <div className="print-only-sheet">
      <div className="print-header">
        <div className="print-char-main">{character}</div>
        <div className="print-char-details">
          <div className="print-title">BẢNG TẬP VIẾT CHỮ HÁN</div>
          <div className="print-row">
            <span className="print-label">Chữ:</span>
            <span className="print-value hanz">{character}</span>
            <span className="print-label" style={{ marginLeft: '20px' }}>Pinyin:</span>
            <span className="print-value">{pinyin}</span>
          </div>
          <div className="print-row">
            <span className="print-label">Nghĩa:</span>
            <span className="print-value">{meaning}</span>
          </div>
        </div>
      </div>

      <div className="print-grid-container">
        {grids.map((_, i) => (
          <div key={i} className="print-grid-box">
            <div className="print-grid-inner">
              <div className="p-line-h" />
              <div className="p-line-v" />
              <div className="p-line-d1" />
              <div className="p-line-d2" />
            </div>
          </div>
        ))}
      </div>

      <footer className="print-footer">
        Generated by Master Xie Hanzi — Chúc bạn học tốt!
      </footer>
    </div>
  );
}
